server:
  port: 8080

spring:
  application:
    name: pick-pay-plataform

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    beans.cache.time-to-live: 10s
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics,info
  metrics:
    export:
      prometheus:
        enabled: true
