server:
  port: 8080

spring:
  application:
    name: pick-pay-plataform

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:/home/wolmir/dbh2teset
    username: sa
    password:

    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      properties:
        hibernate:
          show_sql: true
          format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    beans.cache.time-to-live: 10s
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics,info
  metrics:
    export:
      prometheus:
        enabled: true
